GET http://localhost:3001/patientList

###
GET http://localhost:3001/patientList/6395e2f16e9005285cc726c2

###
POST http://localhost:3001/patientList
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY2RAZ21haWwuY29tIiwiaWQiOiI2Mzk4NWY1YzNjZTQ0ODI5NDM1NTczYTYiLCJpYXQiOjE2NzA5NDc1NTIsImV4cCI6MTY3MDk1MTE1Mn0.tkL7Bb62NALvu11NDbsI5BtolfJ_ZplanMe5noxj4rQ

  {
    "name": "Hello Nepal",
    "contact":239121454,
    "dob":"Dec 19, 1995",
    "email": "hello@gmail.com",
    "profile_pic":"url",
    "city": "554-3052 Park Ave",
    "last_appointment": "Mar 09, 2022",
    "next_appointment": "Apr 16, 2022",
    "register_date": "Feb 1,2022"
  }

###
DELETE http://localhost:3001/patientList/6395e30c2042a97f30e76032

###
PUT  http://localhost:3001/patientList/6395dad7cd5e8ea9e05d70de
content-type: application/json

  {
    "name": "Happy Singh",
    "contact":98470197899,
    "dob":"Nov 9, 1995",
    "email": "singh123@gmail.com",
    "profile_pic":"url",
    "city": "pokhara",
    "last_appointment": "2022-03-18T18:15:00.000Z",
    "next_appointment": "2022-04-09T18:15:00.000Z",
    "register_date": "2022-01-04T18:15:00.000Z"
  }


###
GET http://localhost:3001/users

###
POST http://localhost:3001/users/register
content-type: application/json


 {
  "fullname":"hari padey",
  "email":"abcd@gmail.com",
  "password":"123"
  }


###
POST http://localhost:3001/users/login
content-type: application/json


 {
  "email":"abcd@gmail.com",
  "password":"123"
  }

